### PR TITLE
Introduce wait-timeout-minutes parameter

### LINKED ISSUE #17: Add option to kill tmux session if not connected to within a certain time period
Use case: I've set up my [workflow](https://github.com/kidd/org-gcal.el/blob/master/.github/workflows/main.yml) to automatically run the upterm action if the job fails. This works really well, except for one thing - it causes the action not to complete for hours if there's a failure, because the upterm server just waits there. I could set [`timeout-minutes`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) on the entire step, but that will kill the terminal even if a user connects to it. Instead, I'd like it if there were a `timeout-minutes` field specific to this action that terminates the action if no one SSH's to the server within that number of minutes, but keeps the terminal open if someone connects.

### PR DESCRIPTION
**Pull request by telotortium**
Fix https://github.com/lhotari/action-upterm/issues/17.

Demo: see branch https://github.com/kidd/org-gcal.el/blob/test--wait-timeout-minutes/.github/workflows/main.yml.

I'd like to propose that we tag v1.1 once this is merged, so that other people can easily reference that tag to get this feature.

### CODE REVIEW

**Comment by telotortium** [comment]
Apparently Github is deprecating Node 12 actions in favor of Node 16: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by telotortium** [comment]
Also added a missing mock for `fs.promises.access` to the test to make it pass.

**Comment by telotortium** [comment]
I just saw https://github.com/lhotari/action-upterm/commit/d23c2722bdab893785c9fbeae314cbf080645bd7 - perhaps you will force update the `v1` tag instead, so we won't need to tag `v1.1`?

**Comment by fernandoaleman** [comment]
@lhotari Is this repo still being monitored? This pull request has been open for quite a while.

**Comment by lhotari** [comment]
Great work @telotortium . I'm sorry I have missed handling this PR. I'll process it in the next 24 hrs

**Review by lhotari — APPROVED** [review]

**Pull request merged**
